### PR TITLE
Make PlayState default state in the template.

### PR DESCRIPTION
**Pull request by starry-abyss**
I stumble over it each time I create a new project. "Why the screen is black??" O_O

### CODE REVIEW

**Comment by Gama11** [comment]
Changing this probably confuses all the people who are used to it by now! :D

Maybe there shouldn't be a `MenuState` by default at all...

**Comment by starry-abyss** [comment]
Hmm, who starts developing a game with menu first? Anyone?

**Comment by Gama11** [comment]
Fair enough I guess.

**Comment by starry-abyss** [comment]
Maybe this instead? https://github.com/starry-abyss/flixel-templates/commit/50f8f03c6f41aba1c1b50e29ce19cf8c5fb1643c

**Comment by starry-abyss** [comment]
Of not instead, but together ;-)

**Comment by Gama11** [comment]
Heh, I was 10 seconds faster. :)

I'd like to keep the template simple. Adding texts like that might just annoy people because then they'll have to remove it again because they probably don't need it.

**Comment by starry-abyss** [comment]
OK, so let's "playtest" this change then :D

**Pull request merged**
