### PR TITLE
fix display config paths on linux

### PR DESCRIPTION
**Pull request by 0xFireball**

### CODE REVIEW

**Comment by 0xFireball** [comment]
Completion on Linux with `vshaxe` doesn't work with the default settings file display configuration with path `export/linux/...`. I can verify that changing the path to `export/linux64/...` to match the actual output paths solves the problem, and makes completion work just like on Windows.

**Comment by Gama11** [comment]
Meh. Do you know whether Mac has the same issue?

**Comment by 0xFireball** [comment]
When I build on Linux, the path is `export/mac`

**Comment by Gama11** [comment]
You can build Mac on Linux?!

Well, alright then. Thanks!

**Comment by 0xFireball** [comment]
You can build the `mac` version with `lime build mac -neko`, using Neko

**Comment by 0xFireball** [comment]
You can't build mac CPP though

**Comment by Gama11** [comment]
Ah, I see. Neat.

**Pull request merged**
