### PR TITLE
FlxDemos fdz

### PR DESCRIPTION
**Pull request by PeyTy**
https://github.com/HaxeFlixel/flixel/issues/1753
HOWTO: copy this script and Project.png to /flixel-demos, execute node generate-demos-fdz.js
Contains pregenerated binary

### CODE REVIEW

**Comment by Gama11** [comment]
To be honest, I'm not a huge fan of how this is implemented... There's a lot of manual steps involved. And why not use Haxe instead of JS?
Integrating this into flixel-tools seems like a much better approach. It should already have a lot of the utilites needed. And we have an open TODO for generating .fdz files anyway: https://github.com/HaxeFlixel/flixel-tools/issues/51

**Comment by Gama11** [comment]
Also, I'm not sure if including that 27 MB binary in the repo is a good idea..

**Comment by PeyTy** [comment]
I think PR for FlashDevelop appman may be accepted for now, so users can
use it. Latest Fdz is hosted on my personal repo. We can later discuss
where to rehost it and how to manage updates.

**Comment by Gama11** [comment]
This should be integrated into flixel-demos, but I don't really want to spend the time doing that as we're focusing on improving VSCode support instead these days.

**Pull request closed without merging**
