### PR TITLE
fix exclude blob for vscode

### PR DESCRIPTION
**Pull request by 0xFireball**

### CODE REVIEW

**Comment by Gama11** [comment]
"blob"? Aren't these normally called "glob"? :D

**Comment by 0xFireball** [comment]
i meant glob, mistyped ;P

**Comment by Gama11** [comment]
Oh wow, it's currently so broken it doesn't even let you search.. Pretty sure this used to work - probably broke with the release where they swapped out the "find in files" engine.

Thanks!

**Comment by 0xFireball** [comment]
yeah, this solved the problem on my system 👍

**Pull request merged**
